theme: jekyll-theme-architect

name: Java at Lebanese Java User Group and Cnam Liban

author: Pascal Fares

author_email: pascal.fares@cofares.net

title:  Java at Lebanese Java User Group and Cnam Liban

google_analytics: UA-24954673-1

